feat: Rubygem engine
keygen-sh/keygen-api pull request #889
Opened 2024-09-14 21:55 UTC by mehulmathur16

/closes #491
/claim #491

2024-09-14 22:02 UTC, ezekg requested changes

2024-09-14 22:02 UTC, ezekg commented on app/controllers/api/v1/release_engines/rubygems/simple_controller.rb
> +        pub_date: release.created_at.rfc3339(3),
This is the required format for Tauri, not Rubygems. This does not follow what Rubygems expects, i.e. this won't be installable via `gem install foo --source https://rubygems.pkg.keygen.sh/bar`.

2024-09-14 22:06 UTC, ezekg commented
This isn't really what the issue is describing. Are you sure you understand what's required?

2024-09-14 22:53 UTC, mehulmathur16 commented
@ezekg I'll review the details in issue #491 again to ensure I'm fully aligned with the requirements.

2024-09-15 01:12 UTC, ezekg commented
There's implementations like [Gitea's](https://github.com/KN4CK3R/gitea/blob/4b1f387cb90e15d0f1659b96df6a283f98c65438/routers/api/packages/rubygems/rubygems.go), [GitLab's](https://github.com/gitlabhq/gitlabhq/tree/2b42932ce5871c9c240aa9a56745cec8807c3876/app/services/packages/rubygems), and [Rubygems.org](https://github.com/rubygems/rubygems.org) to study for a general idea of what I'm thinking here. In the end, I want a user to be able to upload a `.gem` file, and essentially automate all of the manual work in [this blog post](https://keygen.sh/blog/how-to-license-and-distribute-a-private-rubygem/) — ultimately allowing a user to `gem install` the package like a normal gem from https://rubygems.org.

2024-09-29 13:43 UTC, ezekg commented
Closing due to inactivity. Feel free to open a new PR if you pick this up again. 👍

2024-09-29 13:43 UTC, closed without merging